n=int(input('Digite um número!'))
print('O número {} têm como antecessor {} e como sucessor {}'.format(n,n-1,n+1))
print('O Dobro de {} será {}'.format(n,n*2))
print('O Triplo de {} será {}'.format(n,n*3))
print('A raiz quadrada de {} será {:.2f}'.format(n,n**(1/2)))