print("Hello Word!")
nome = input("Qual o seu nome?")
dia_nasceu = input("Dia que você nasceu?")
mes = input("Em que mês você nasceu?")
idade = input("Em que ano você nasceu?")
print("Olá", nome + "! Seja Bem vindo!")
print("Você nasceu dia", dia_nasceu, "de", mes, "no ano de", idade)
