nome = input("Digite seu nome! ")
print('Seu nome todo maiusculo: {}!'.format(nome.upper()))
print('Seu nome todo minusculo: {}!'.format(nome.lower()))
d = nome.split()
print('Seu nome sem espaços tem {} letras!'.format(len("".join(d))))
print('O seu primeiro nome têm {} letras!'.format(len(d[0])))
